title: João Pedro
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  Estudante de Engenharia Elétrica e Cientista de Dados em formação. 
  <br><br>
  Ativista climático e pregador do objetivo de desenvolvimento sustentável 7 da ONU. 
  <br><br>
  <a href="https://www.linkedin.com/in/jo%C3%A3o-pedro-ara%C3%BAjo-bonfim-0368b723a/">Meu perfil do LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
