title: Ol√° üëã, me chamo Jo√£o Pedro
logo: "/images/logo.png?raw=true" 
description: > 
  Estudante de Engenharia El√©trica e Cientista de Dados em forma√ß√£o. 
  <br><br>
  Ativista clim√°tico e pregador do objetivo de desenvolvimento sustent√°vel 7 da ONU. 
  <br><br>
  <a href="https://www.linkedin.com/in/jo%C3%A3o-pedro-ara%C3%BAjo-bonfim-0368b723a/">Meu perfil do LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
